# Generated by Django 2.0.5 on 2018-05-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Parcheggio',
                'verbose_name_plural': 'Parcheggi',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ParkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('nowstamp', models.DateTimeField(blank=True, null=True)),
                ('webstamp', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('full', models.IntegerField(default=0)),
                ('free', models.IntegerField(default=0)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='park_server_core.Park')),
            ],
            options={
                'verbose_name': 'Dati parcheggio',
                'verbose_name_plural': 'Dati parcheggio',
                'ordering': ['park', 'stamp'],
            },
        ),
        migrations.CreateModel(
            name='ParkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('nowstamp', models.DateTimeField(blank=True, null=True)),
                ('webstamp', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('full', models.IntegerField(default=0)),
                ('free', models.IntegerField(default=0)),
                ('park', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='park_server_core.Park')),
            ],
            options={
                'verbose_name': 'Stato parcheggio',
                'verbose_name_plural': 'Stati parcheggio',
                'ordering': ['park', 'stamp'],
            },
        ),
    ]
